import React, { createContext, useContext, useState, useEffect } from 'react';

const AppContext = createContext();

export const translations = {
    es: {
        appName: 'FinanziApp',
        dashboard: 'Dashboard',
        monthly: 'Seguimiento Mensual',
        networth: 'Patrimonio Neto',
        loans: 'Préstamos',
        settings: 'Configuración',
        signOut: 'Cerrar Sesión',
        loading: 'Cargando...',
        initiating: 'Iniciando datos...',
        noData: 'No hay datos para',
        income: 'Ingresos',
        expenses: 'Gastos',
        savings: 'Ahorro / Déficit',
        totalYear: 'Total Año',
        monthlyIncome: 'Ingresos vs. Gastos Mensuales',
        expenseDist: 'Distribución de Gastos',
        budgetVsActual: 'Presupuesto vs. Real',
        annualSummary: 'Resumen Anual por Categoría',
        totalGeneral: 'Total General',
        totalReal: 'Total Real',
        category: 'Categoría',
        monthlyAmount: 'Cantidad Mensual',
        monthlyBudget: 'Presupuesto Mensual',
        remainder: 'Remanente',
        budgetSummary: 'Resumen Presupuesto',
        concept: 'Concepto',
        budget: 'Presupuesto',
        percentage: 'Porcentaje',
        addTransaction: 'Añadir Transacción',
        mainCategory: 'Categoría Principal',
        subCategory: 'Subcategoría',
        date: 'Fecha',
        amount: 'Valor',
        add: 'Añadir',
        transactions: 'Transacciones',
        noTransactions: 'No hay transacciones para este mes.',
        actions: 'Acciones',
        netWorthEvolution: 'Evolución del Patrimonio Neto',
        assets: 'Activos',
        liabilities: 'Pasivos',
        netWorth: 'Patrimonio Neto',
        generalSettings: 'Configuración General',
        defaultYear: 'Año por Defecto',
        categoryManager: 'Gestor de Categorías',
        addSubcategory: 'Añadir Subcategoría en',
        newSubcategoryName: 'Nombre de la nueva subcategoría',
        cancel: 'Cancelar',
        confirmDelete: 'Confirmar Eliminación',
        deleteWarning: '¡Atención! Esto eliminará permanentemente todos los datos asociados.',
        delete: 'Eliminar',
        addMainCategory: 'Añadir Nueva Categoría Principal',
        createMainCategory: 'Crear Categoría Principal',
        language: 'Idioma',
        theme: 'Tema',
        darkMode: 'Modo Oscuro',
        lightMode: 'Modo Claro',
        charts: 'Gráficos',
        budgetMode: 'Presupuesto',
        year: 'Año',
        month: 'Mes',
        collapseMenu: 'Colapsar Menú',
        expandMenu: 'Expandir Menú',
        incomeSummary: 'Resumen de Ingresos',
        expenseSummary: 'Resumen de Gastos',
        budgeted: 'Presupuestado',
        real: 'Real',
        difference: 'Diferencia',
        essentialExpenses: 'Gastos Esenciales',
        discretionaryExpenses: 'Gastos Discrecionales',
        debtPayments: 'Pago de Deudas',
        savingsInvestment: 'Ahorro e Inversión',
        essentialPlusDiscretionary: 'Esenciales + Discrecionales',
        oneTimeExpenses: 'Gastos Puntuales',
        addOneTime: 'Añadir Gasto Puntual',
        loanManagement: 'Gestión de Préstamos e Hipotecas',
        loanName: 'Nombre del Préstamo',
        loanTotal: 'Importe del Préstamo',
        installments: 'Número de Cuotas',
        installment: 'Cuota Mensual',
        startDate: 'Fecha Inicio',
        endDate: 'Fecha Fin',
        remaining: 'Restante',
        calendar: 'Calendario de Pagos',
        interestRate: 'Tipo de Interés (%)',
        interest: 'Intereses',
        principal: 'Amortización Capital',
        totalAmortized: 'Capital Amortizado',
        pendingCapital: 'Capital Pendiente',
        paymentNo: 'Nº Cuota',
        active: 'Activo',
        finished: 'Finalizado',
        budgetLock: 'Bloquear Presupuesto',
        budgetUnlock: 'Habilitar Edición',
        loanLocked: 'Préstamos (editar en pestaña Préstamos)',
        noLoans: 'No hay préstamos configurados.',
        totalOwed: 'Total Pendiente',
        totalIncome: 'Ingresos Totales',
        totalExpenses: 'Gastos Totales',
        savingsRate: 'tasa de ahorro',
        ofIncome: 'del ingreso',
        monthlyAvg: 'mes avg',
        loanProgress: 'Progreso de Préstamos',
        netWorthSummary: 'Resumen Patrimonio',
        tradingSummary: 'Resumen Trading',
        winRate: 'Win Rate',
        totalPnL: 'P&L Total',
        totalTrades: 'Operaciones',
        annual: 'Anual',
        monthlyLabel: 'Mensual',
        projectionDetail: 'Detalle de la Proyección',
        accInterest: 'Intereses Acum.',
        monthInterestLabel: 'Interés Mes',
        contribution: 'Contribución',
        totalBalance: 'Balance Total',
        investedCapital: 'Capital Invertido',
        initialStart: 'Inicio',
        zoomPrompt: 'Arrastra la barra inferior para hacer zoom en un período específico'
    },
    en: {
        appName: 'FinanziApp',
        dashboard: 'Dashboard',
        monthly: 'Monthly Tracker',
        networth: 'Net Worth',
        loans: 'Loans',
        settings: 'Settings',
        signOut: 'Sign Out',
        loading: 'Loading...',
        initiating: 'Initializing data...',
        noData: 'No data for',
        income: 'Income',
        expenses: 'Expenses',
        savings: 'Savings / Deficit',
        totalYear: 'Total Year',
        monthlyIncome: 'Income vs. Monthly Expenses',
        expenseDist: 'Expense Distribution',
        budgetVsActual: 'Budget vs. Actual',
        annualSummary: 'Annual Summary by Category',
        totalGeneral: 'Grand Total',
        totalReal: 'Total Actual',
        category: 'Category',
        monthlyAmount: 'Monthly Amount',
        monthlyBudget: 'Monthly Budget',
        remainder: 'Remainder',
        budgetSummary: 'Budget Summary',
        concept: 'Concept',
        budget: 'Budget',
        percentage: 'Percentage',
        addTransaction: 'Add Transaction',
        mainCategory: 'Main Category',
        subCategory: 'Subcategory',
        date: 'Date',
        amount: 'Amount',
        add: 'Add',
        transactions: 'Transactions',
        noTransactions: 'No transactions for this month.',
        actions: 'Actions',
        netWorthEvolution: 'Net Worth Evolution',
        assets: 'Assets',
        liabilities: 'Liabilities',
        netWorth: 'Net Worth',
        generalSettings: 'General Settings',
        defaultYear: 'Default Year',
        categoryManager: 'Category Manager',
        addSubcategory: 'Add Subcategory in',
        newSubcategoryName: 'New subcategory name',
        cancel: 'Cancel',
        confirmDelete: 'Confirm Deletion',
        deleteWarning: 'Warning! This will permanently delete all associated data.',
        delete: 'Delete',
        addMainCategory: 'Add New Main Category',
        createMainCategory: 'Create Main Category',
        language: 'Language',
        theme: 'Theme',
        darkMode: 'Dark Mode',
        lightMode: 'Light Mode',
        charts: 'Charts',
        budgetMode: 'Budget',
        year: 'Year',
        month: 'Month',
        collapseMenu: 'Collapse Menu',
        expandMenu: 'Expand Menu',
        incomeSummary: 'Income Summary',
        expenseSummary: 'Expense Summary',
        budgeted: 'Budgeted',
        real: 'Actual',
        difference: 'Difference',
        essentialExpenses: 'Essential Expenses',
        discretionaryExpenses: 'Discretionary Expenses',
        debtPayments: 'Debt Payments',
        savingsInvestment: 'Savings & Investment',
        essentialPlusDiscretionary: 'Essential + Discretionary',
        savingsTotal: 'Total Savings & Investment',
        oneTimeExpenses: 'One-time Expenses',
        addOneTime: 'Add One-time Expense',
        loanManagement: 'Loans & Mortgages Management',
        loanName: 'Loan Name',
        loanTotal: 'Total Amount',
        installments: 'Installments',
        installment: 'Installment',
        interestRate: 'Interest Rate (%)',
        interest: 'Interest',
        principal: 'Principal',
        totalAmortized: 'Total Amortized',
        pendingCapital: 'Remaining Balance',
        paymentNo: 'No.',
        startDate: 'Start Date',
        endDate: 'End Date',
        remaining: 'Remaining',
        calendar: 'Amortization Table',
        active: 'Active',
        finished: 'Finished',
        budgetLock: 'Lock Budget',
        budgetUnlock: 'Enable Editing',
        loanLocked: 'Loans (edit in Loans tab)',
        noLoans: 'No loans configured.',
        totalOwed: 'Total Owed',
        totalIncome: 'Total Income',
        totalExpenses: 'Total Expenses',
        savingsRate: 'savings rate',
        ofIncome: 'of income',
        monthlyAvg: 'month avg',
        loanProgress: 'Loan Progress',
        netWorthSummary: 'Net Worth Summary',
        tradingSummary: 'Trading Summary',
        winRate: 'Win Rate',
        totalPnL: 'Total P&L',
        totalTrades: 'Trades',
        annual: 'Annual',
        monthlyLabel: 'Monthly',
        projectionDetail: 'Projection Detail',
        accInterest: 'Acc. Interest',
        monthInterestLabel: 'Month Interest',
        contribution: 'Contribution',
        totalBalance: 'Total Balance',
        investedCapital: 'Invested Capital',
        initialStart: 'Initial',
        zoomPrompt: 'Drag the bottom bar to zoom in on a specific period'
    },
    de: {
        appName: 'FinanziApp',
        dashboard: 'Dashboard',
        monthly: 'Monatliche Verfolgung',
        networth: 'Nettovermögen',
        loans: 'Kredite',
        settings: 'Einstellungen',
        signOut: 'Abmelden',
        loading: 'Laden...',
        initiating: 'Daten werden initialisiert...',
        noData: 'Keine Daten für',
        income: 'Einkommen',
        expenses: 'Ausgaben',
        savings: 'Ersparnisse / Defizit',
        totalYear: 'Gesamtjahr',
        monthlyIncome: 'Einkommen vs. Monatliche Ausgaben',
        expenseDist: 'Ausgabenverteilung',
        budgetVsActual: 'Budget vs. Tatsächlich',
        annualSummary: 'Jahreszusammenfassung nach Kategorie',
        totalGeneral: 'Gesamtsumme',
        totalReal: 'Tatsächliche Summe',
        category: 'Kategorie',
        monthlyAmount: 'Monatlicher Betrag',
        monthlyBudget: 'Monatsbudget',
        remainder: 'Restbetrag',
        budgetSummary: 'Budgetübersicht',
        concept: 'Konzept',
        budget: 'Budget',
        percentage: 'Prozentsatz',
        addTransaction: 'Transaktion hinzufügen',
        mainCategory: 'Hauptkategorie',
        subCategory: 'Unterkategorie',
        date: 'Datum',
        amount: 'Betrag',
        add: 'Hinzufügen',
        transactions: 'Transaktionen',
        noTransactions: 'Keine Transaktionen für diesen Monat.',
        actions: 'Aktionen',
        netWorthEvolution: 'Nettovermögensentwicklung',
        assets: 'Vermögenswerte',
        liabilities: 'Verbindlichkeiten',
        netWorth: 'Nettovermögen',
        generalSettings: 'Allgemeine Einstellungen',
        defaultYear: 'Standardjahr',
        categoryManager: 'Kategorieverwaltung',
        addSubcategory: 'Unterkategorie hinzufügen in',
        newSubcategoryName: 'Name der neuen Unterkategorie',
        cancel: 'Abbrechen',
        confirmDelete: 'Löschen bestätigen',
        deleteWarning: 'Achtung! Dadurch werden alle zugehörigen Daten dauerhaft gelöscht.',
        delete: 'Löschen',
        addMainCategory: 'Neue Hauptkategorie hinzufügen',
        createMainCategory: 'Hauptkategorie erstellen',
        language: 'Sprache',
        theme: 'Thema',
        darkMode: 'Dunkler Modus',
        lightMode: 'Heller Modus',
        charts: 'Diagramme',
        budgetMode: 'Budget',
        year: 'Jahr',
        month: 'Monat',
        collapseMenu: 'Menü einklappen',
        expandMenu: 'Menü ausklappen',
        incomeSummary: 'Einkommensübersicht',
        expenseSummary: 'Ausgabenübersicht',
        budgeted: 'Budgetiert',
        real: 'Tatsächlich',
        difference: 'Differenz',
        essentialExpenses: 'Wesentliche Ausgaben',
        discretionaryExpenses: 'Freiwillige Ausgaben',
        debtPayments: 'Schuldentilgung',
        savingsInvestment: 'Sparen & Investition',
        essentialPlusDiscretionary: 'Wesentlich + Freiwillig',
        savingsTotal: 'Gesamtersparnisse & Investitionen',
        oneTimeExpenses: 'Einmalige Ausgaben',
        addOneTime: 'Einmalige Ausgabe hinzufügen',
        loanManagement: 'Kredit- & Hypothekenverwaltung',
        loanName: 'Kreditname',
        loanTotal: 'Gesamtbetrag',
        installments: 'Raten',
        installment: 'Rate',
        interestRate: 'Zinssatz (%)',
        interest: 'Zinsen',
        principal: 'Tilgung',
        totalAmortized: 'Gesamttilgung',
        pendingCapital: 'Restschuld',
        paymentNo: 'Nr.',
        startDate: 'Startdatum',
        endDate: 'Enddatum',
        remaining: 'Verbleibend',
        calendar: 'Tilgungsplan',
        active: 'Aktiv',
        finished: 'Abgeschlossen',
        budgetLock: 'Budget sperren',
        budgetUnlock: 'Bearbeitung aktivieren',
        loanLocked: 'Kredite (im Reiter Kredite bearbeiten)',
        noLoans: 'Keine Kredite konfiguriert.',
        totalOwed: 'Gesamtschulden',
        totalIncome: 'Gesamteinkommen',
        totalExpenses: 'Gesamtausgaben',
        savingsRate: 'Sparquote',
        ofIncome: 'des Einkommens',
        monthlyAvg: 'Monat Ø',
        loanProgress: 'Kreditfortschritt',
        netWorthSummary: 'Vermögensübersicht',
        tradingSummary: 'Trading-Übersicht',
        winRate: 'Gewinnrate',
        totalPnL: 'Gesamt-P&L',
        totalTrades: 'Trades',
        annual: 'Jährlich',
        monthlyLabel: 'Monatlich',
        projectionDetail: 'Projektionsdetails',
        accInterest: 'Aufgelaufene Zinsen',
        monthInterestLabel: 'Monatszinsen',
        contribution: 'Beitrag',
        totalBalance: 'Gesamtbalance',
        investedCapital: 'Investiertes Kapital',
        initialStart: 'Anfang',
        zoomPrompt: 'Ziehen Sie den unteren Balken, um einen bestimmten Zeitraum heranzuzoomen'
    }
};

export function AppProvider({ children }) {
    const [theme, setTheme] = useState(() => localStorage.getItem('appTheme') || 'dark');
    const [language, setLanguage] = useState(() => localStorage.getItem('appLanguage') || 'es');

    useEffect(() => {
        localStorage.setItem('appTheme', theme);
        document.documentElement.classList.toggle('dark', theme === 'dark');
        document.documentElement.classList.toggle('light', theme === 'light');
    }, [theme]);

    useEffect(() => {
        localStorage.setItem('appLanguage', language);
    }, [language]);

    const t = translations[language];

    const toggleTheme = () => setTheme(prev => prev === 'dark' ? 'light' : 'dark');
    const toggleLanguage = () => setLanguage(prev => prev === 'es' ? 'en' : prev === 'en' ? 'de' : 'es');
    const setLanguageTo = (lang) => setLanguage(lang);

    return (
        <AppContext.Provider value={{ theme, toggleTheme, language, toggleLanguage, setLanguageTo, t }}>
            {children}
        </AppContext.Provider>
    );
}

export function useApp() {
    return useContext(AppContext);
}
